[book]
authors = ["BigMike"]
language = "en"
multilingual = false
src = "src"
title = "Token Price Manager/Controller Functionality"

[build]
build-dir = "../docs/"

[output.html]
copy-fonts = false
no-section-label = true
default-theme = "rust"
preferred-dark-theme = "ayu"